### ISSUE TITLE
"pip install readme" fails on Windows + Miniconda

### ISSUE THREAD

**Issue by edisongustavo** [pypa/readme#31] opened 2015-06-15 19:14 UTC
I'm trying to install the [restview library](https://pypi.python.org/pypi/restview) and it depends on the `readme` library.

I'm getting this error though:

```
C:\
λ pip install readme
Collecting readme
  Using cached readme-0.5.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): docutils in c:\miniconda\lib\site-packages (from readme)
Requirement already satisfied (use --upgrade to upgrade): Pygments in c:\miniconda\lib\site-packages (from readme)
Requirement already satisfied (use --upgrade to upgrade): six in c:\miniconda\lib\site-packages (from readme)
Requirement already satisfied (use --upgrade to upgrade): bleach in c:\miniconda\lib\site-packages (from readme)
Requirement already satisfied (use --upgrade to upgrade): html5lib>=0.999 in c:\miniconda\lib\site-packages (from bleach->readme)
Installing collected packages: readme
Exception:
Traceback (most recent call last):
  File "C:\Miniconda\lib\site-packages\pip\basecommand.py", line 223, in main
    status = self.run(options, args)
  File "C:\Miniconda\lib\site-packages\pip\commands\install.py", line 297, in run
    root=options.root_path,
  File "C:\Miniconda\lib\site-packages\pip\req\req_set.py", line 622, in install
    **kwargs
  File "C:\Miniconda\lib\site-packages\pip\req\req_install.py", line 808, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "C:\Miniconda\lib\site-packages\pip\req\req_install.py", line 1003, in move_wheel_files
    isolated=self.isolated,
  File "C:\Miniconda\lib\site-packages\pip\wheel.py", line 339, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Miniconda\lib\site-packages\pip\wheel.py", line 317, in clobber
    shutil.copyfile(srcfile, destfile)
  File "C:\Miniconda\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: 'C:\\Miniconda\\Lib\\site-packages\\readme\\clean.py'
```

These are the versions of conda and pip that I'm using:

```
C:\
λ conda -V
conda 3.11.0-dirty

C:\
λ pip --version
pip 7.0.3 from C:\Miniconda\lib\site-packages (python 2.7)
```

I'm using Windows 7 64 bits

**Comment by jonafato** [comment] 2015-07-13 20:59
This seems like a duplicate of #26. The fix here would probably require a renaming.

**Comment by scls19fr** [comment] 2015-07-14 06:48
see mgedmin/restview#30
also pypa/pip#2821
and https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/AGHXzB1sN0I

**Comment by scls19fr** [comment] 2015-07-14 08:08
http://bugs.python.org/issue24633

**Closed** 2016-01-04 20:41 UTC

**Comment by reinout** [comment] 2016-01-04 21:31
Will the package stay available as `readme`, too, on pypi? I'd hate to see (for instance) `zest.releaser` installs fail ;-)

**Comment by jezdez** [comment] 2016-01-04 21:42
@reinout I've released readme 0.7.0 that raises an exception on install. If you pin to readme<0.7.0 you should be good.

**Comment by reinout** [comment] 2016-01-05 08:01
"Should be good" means "this just broke every package that has 'readme' as a dependency". A warning would have been much better.

I mean, the original readme package works fine in most places. At least, I haven't had any bug reports for zest.releaser because it wouldn't install. I'll of course issue a new release that depends on the new package name.

But existing zest.releaser versions would have worked just fine with 'readme', but now their install is terminated because of the error that is raised.

Could you release a 0.7.1 that only prints a warning? (Loud warning is fine, of course :-) )

**Comment by jezdez** [comment] 2016-01-05 08:57
@reinout This is tracked in #40 now.
